### ISSUE TITLE
CocoaKucha 2 - London

### ISSUE THREAD

**Issue by orta** [orta/life#10]
##### Setup
- [x] Date 16th Jan
- [x] Venue sorted
- [ ] Pizza & Beer etc
- [ ] My travel is booked
- [ ] Flights for Fabio?
- [ ] Blog post & Announcements
##### Speakers
- [x] Stig Brautaset (SBJSON) 
- [x] Alex Rozanski ( PXSourceList ) 
- [x] Damien DeVille ( DDWhatever )
- [x] Rolandas Razma ( Backporting )
- [ ] Ben Copsey ( ASI ) ( emailed )
- [x] James Addyman ( iOS emulators )
- [x] Fabio Pelosin ( Whatever he wants ) ( said 99% sure is there )
- [x] Luca Bernardi ( Multiple delegate pattern )
#### No
- [ ] Tony Million ( Reachability or TMNetworking? ) ( emailed, out in SF, not possible )

**Comment by orta** [comment]
Done & dusted. Thanks!

Slides: 
- Lucas: https://speakerdeck.com/lucabernardi/multicast-delegation

**Comment by RolandasRazma** [comment]
my slides http://www.slideshare.net/RolandasRazma/ios-backports
