### ISSUE TITLE
Weekly videocast where I run through an OSS library

### ISSUE THREAD

**Issue by orta** [orta/life#11]
Pick a pod
Run `pod try X`
Video going through the code, doing code review, picking out things I like, things I don't like and saying how the library works.

Like Day9TV [dailys](http://day9.tv/d/Day9/day9-daily-655-scarlett-vs-bomber-the-best-sc2-game-in-history/) for open source.

**Comment by orta** [comment]
got the ball rolling with @1aurabrown

**Comment by neonichu** [comment]
👍

**Comment by orta** [comment]
I outsourced this idea on my blog, hard enough doing pod5 once a week.
