### ISSUE TITLE
CocoaKucha 3 - Berlin

### ISSUE THREAD

**Issue by orta** [orta/life#17]
### Setup
- [x] Part of [CocoaHeads berlin](http://cocoaheads.org/de/Berlin/index.html)
- [x] Potential date of 22nd Jan
### Speakers

From CocoaPods:
- [ ] Alloy? No coming
- [x] Florian Hanke? Confirmed

Ich bin ein Berliner:
- [x] Claudiu on [CPAProxy](https://github.com/ursachec/CPAProxy) (confirmed)
- [ ] Ole Zorn on [Xcode plugins](https://github.com/omz) (emailed, twice)
- [ ] Markus Emrich [JSXXXViews](https://github.com/jaydee3) (emailed, tweeted)
- [ ] Martin Hwasser  (maybe but unlikely)
- [ ] [Anouk Ruhaak](http://www.djipsy.com/) (emailed)
- [ ] [Naja von Schmude](http://develop.najavonschmude.de)

Blog Post : http://blog.cocoapods.org/Cocoa-Kucha-3-Berlin/

**Comment by JMSerruya** [comment]
Hey!, this sounds amazing. I could prepare a small talk about my work at http://How.do but happier to be just an attendee since this month is a bit crazy for me :)

**Comment by orta** [comment]
@JMSerruya I think that'd be really interesting. Personally, I'd love to have you talk about it. You should do it. [Add yourself](https://github.com/CocoaPods/blog.cocoapods.org/edit/master/_posts/2014-01-08-Cocoa-Kucha-3-Berlin.markdown).

**Comment by JMSerruya** [comment]
I think i just did, ha

**Comment by orta** [comment]
Woo, closing!
