### ISSUE TITLE
[Easy First Step] Give @irrationalfab his lightning cable

### ISSUE THREAD

**Issue by kylef** [orta/life#22]
This should be an easy first step, take it to Amsterdam when you attend [mdevcon](http://mdevcon.com).

![](http://media.giphy.com/media/ZNc8TahjD8ZFe/giphy.gif)

/cc @irrationalfab

**Comment by fabiopelosin** [comment]
Thanks @kylef! :smile:

**Comment by orta** [comment]
Hrm, I seem to be down to only one cable, they come and go so much :dancer:

**Comment by fabiopelosin** [comment]
So should I consider mine MIA?

**Comment by orta** [comment]
Done'd

**Comment by fabiopelosin** [comment]
:+1:
