### ISSUE TITLE
MDevCon 

### ISSUE THREAD

**Issue by orta** [orta/life#23]
### People
- [x] Find out How many people are going
- [x] Get @alloy to look at apartments / airbnb
- [ ] Make sure @irrationalfab has done his speakers forms
### Me & Fabio
- [ ] Discuss idea of talk
- [ ] Mock up slides
- [ ] Ensure we've gone over them remotely

**Comment by alloy** [comment]
Find out How many people are going **and** when they will be here.

**Comment by Lascorbe** [comment]
People:
- Kyle (7th - 9th)
- Orta (7th - 9th)
- Fabio (7th - 9th)
- Luis (6th - 9th)
- Rafa (6th - 9th)

Rafa is a friend that works in the company I'm joining to.

**Comment by Lascorbe** [comment]
Place: This is what I've found, how it looks?

https://www.airbnb.es/rooms/1882314?checkin=06%2F03%2F2014&checkout=09%2F03%2F2014&guests=5&s=yw1Q

**Comment by alloy** [comment]
This isn’t very close to the venue, nor that handy at all to access the city as it’s located north of the ‘IJ’ river:

![screen shot 2014-01-22 at 17 48 19](https://f.cloud.github.com/assets/2320/1976026/1b0df224-8385-11e3-94ad-82fbfb6c0653.png)

**Comment by Lascorbe** [comment]
Definitely I'm not the guy to look for it :sweat_smile:

**Comment by alloy** [comment]
Ideally you would find something around here:

![screen shot 2014-01-22 at 17 52 47](https://f.cloud.github.com/assets/2320/1976094/09075b46-8386-11e3-8b1e-160f01077369.png)

**Comment by Lascorbe** [comment]
This one?

https://www.airbnb.es/rooms/740995?checkin=06%2F03%2F2014&checkout=09%2F03%2F2014&guests=5&s=64up

**Comment by alloy** [comment]
Love Nest. Looks perfect :+1:

**Comment by Lascorbe** [comment]
This one is cool too.

https://www.airbnb.es/rooms/728144?checkin=07%2F03%2F2014&checkout=09%2F03%2F2014&guests=5&s=614x

if only rafa and me are going on 6th, maybe we should go to another place the first night.

**Comment by alloy** [comment]
That one is really around the corner of the venue, which can be cool if you quickly want to drop off bags etc.

**Comment by orta** [comment]
This latest one looks good to me

**Comment by rais38** [comment]
The latest seems really nice!!!

Take the opportunity for introduce myself, my name is Rafa and i will be the new partner of Luis ;)

**Comment by Lascorbe** [comment]
Ace! :beers: 

Who can rent it?

**Comment by orta** [comment]
If we get confirmation from everyone I can book it and give everyone my bank details for splitting.

**Comment by Lascorbe** [comment]
Perfect :+1:

**Comment by Lascorbe** [comment]
All d'accord with this, WDYT @irrationalfab? :smile:

**Comment by Lascorbe** [comment]
@orta since Fabio would get there the same days, can we book it already? I really don't wanna lose the flat :)

**Comment by orta** [comment]
I have asked for our booking

**Comment by fabiopelosin** [comment]
Sounds awesome!

**Comment by fabiopelosin** [comment]
> Make sure @irrationalfab has done his speakers forms

Done! I’ve uniformed to the 7th - 9th bandwagon.

## 

The place looks terrific! Awesome work guys!

**Comment by Lascorbe** [comment]
:beers:

**Comment by Lascorbe** [comment]
Are you joining this the first night? http://www.meetup.com/mdevcon/events/163253542/

**Comment by orta** [comment]
I was planning on doing those events I don't like it when speakers hide off on their own, I'll probably arrive at our AirBnB around 12-1 isn midday tomorrow. 

Our host is called Mirjam, I'll probably arrive at the place, send a ping out on our glassboard ( @rais38 get the invite code from @Lascorbe ( get the invite from Campfire ) )  to find everyones times / dates, push any work from the plane then start schmoozing.

I've invited along a buddy of mine @hampei who should be doing some hanging with us too, he's cool.

/cc @kylef

**Comment by orta** [comment]
Also, 

> > About the check-out time: sunday other guests arrive, but you can leave your luggage in the house and pick it up when you're heading to the airport. I hope this is okay for you.

**Comment by alloy** [comment]
@orta Ping me when you arrive at the apartment and I’ll come over!

**Comment by orta** [comment]
:+1:

**Comment by alloy** [comment]
ALL: Can you create a list of how late you arrive? We need to find time for some quality discussing and hacking, especially regarding the trunk app.

**Comment by fabiopelosin** [comment]
My plane lands at 14:30, so I expect to be at the apartment before 16:00.

**Comment by kylef** [comment]
@kylef: 08:35 PM at AMS.

**Comment by Lascorbe** [comment]
@orta Everything cool, see you tomorrow :smile: :beers:

**Comment by orta** [comment]
Ace. Worked.
