### ISSUE TITLE
CocoaKucha Barcelona

### ISSUE THREAD

**Issue by Lascorbe** [orta/life#27]
Hey Orta, 

as we talked about this, do you think we can organize one in April-May?

**Comment by orta** [comment]
I think it's gonna have to be later for me, I don't have any spare travel time till June-July I think :/

**Comment by Lascorbe** [comment]
Damn, no worries, we can talk at mdevcon then :)

**Comment by Lascorbe** [comment]
Hey Orta! What about doing it on July 19, would you be able to come? :smile: cc @neonichu @irrationalfab @kylef @hpique

**Comment by neonichu** [comment]
I'll be in. Coming to BCN 17 - 19 if it happens.

**Comment by orta** [comment]
OK, calling this not happening for the moment :+1:
