### ISSUE TITLE
Get new CocoaPods Stickers bought.

### ISSUE THREAD

**Issue by orta** [orta/life#29]
Need to ping @andyrmyers about an updated Ai file.
And get them in CocoaPods Orange.

**Comment by andyrmyers** [comment]
Orta! I quit twitter so you'll have to catch me on email from now on. Sorry for my absence. Gearing up for the Winter Olympics.

**Comment by orta** [comment]
That explained why I couldn't find you to reference on my updated website, hah.
Understandable of course.

The only change needed is that the `PODS>` had a margin on the type so it didn't align with the `COCOA`

![screen shot 2014-02-04 at 09 58 08](https://f.cloud.github.com/assets/49038/2077100/c6f263d2-8dac-11e3-8308-8912305af054.png)

**Comment by andyrmyers** [comment]
OK, it looks like there's a stroke on the Pods which is causing it. 

I noticed on the blog the italicising of paragraphs of text. I would advise against that as italics are difficult to read.

**Comment by orta** [comment]
Strokes the word, thanks.

Think the italics that makes sense.

**Comment by orta** [comment]
bought.
