### ISSUE TITLE
Get to a CocoaHeads Stockholm event

### ISSUE THREAD

**Issue by orta** [orta/life#30]
In reference to @d-ronnqvist's tweet: 

https://twitter.com/davidronnqvist/status/434371464268349440

I know this seems forever away but my next free week in europe is in July, I could try arrange this to coincide (by my travel plans) with #27. Potentially mid-late july towards the end of the week?

**Comment by marthinfreij** [comment]
Hi! I'm the organizer of CocoaHeads Stockholm. It would be awesome to have you visit one of our meetings! Usually we have our meetings the first monday each month, but I guess that could be flexible to match your schedule. July is traditionally the vacation month in Sweden, meaning most of the people leave town and it could be tricky to find a good venue etc. Toss me a few dates both in July but if possible also in August and September and I will see what I can do!

**Comment by orta** [comment]
Hey @marthinfreij I was just thinking out loud, a monday can work for me too also, as me & my girlfriend can come over for the weekend and I'll just stay and do some remote work for a few days during the week then head back over. 

My July is totally free atm so I'm open for aiming at the first monday in july?

**Comment by marthinfreij** [comment]
Sounds great! I will check if July would work for us. How about May, August or September if July doesn't work for us?

**Comment by marthinfreij** [comment]
Hi again! We might have something great going on for May 19th. Are you available that date?

**Comment by orta** [comment]
It's looking a bit hard to guess when I'm next going to be in Europe ATM, as I need to contrast my EU time with being in the Artsy office. So for now it might be worth bringing up around sept time as I was thinking of coming back for NSSpain so could try get around then ;)

**Comment by orta** [comment]
June is looking good for me, is that still free? https://github.com/orta/travel/

**Comment by d-ronnqvist** [comment]
Bot June and July (I'm not sure which you meant) are still free but we don't have any big plans for either of them at the moment. Lot's of Swedes are on vacations during the summer so there will probably be a smaller event.

**Comment by orta** [comment]
Hey hey everyone, I've got flights booked out now, I'll be heading out early on the 4th of July, and aim to be heading out maybe on the 8th or 9th, that's not booked yet. So I don't know what day in that date range works for you guys but I'm open to any.

I was thinking of grabbing an Airbnb in [the centre](https://www.airbnb.com/rooms/1871456?checkin=07%2F04%2F2014&checkout=07%2F07%2F2014&guests=2&s=mDHY) whilst my girlfriend is over ( she leaves monday morning ), if either of you guys has a couch I could crash on mon/tuesday that'd be awesome.

**Comment by orta** [comment]
Also, I think [Robert Lenne](http://firstround.com/article/artsy), head of design at Artsy & the designer of the [Artsy iOS app](http://iphone.artsy.net) is around in Stockholm too, I can ping him if you're interested?

**Comment by d-ronnqvist** [comment]
If Robert is in Stockholm and want to talk about something that would be cool. I'll get back to you with details as soon as I can.

**Comment by d-ronnqvist** [comment]
P.s. 
Chris asked me to tell you to talk about something other than CocoaPods ;)
D.s.

**Comment by orta** [comment]
DONE!
