### ISSUE TITLE
CocoaPods Bug Bash notes

### ISSUE THREAD

**Issue by orta** [orta/life#32]
- [ ] Get date sorted
- [ ] Get prizes
- [ ] IRC Bot for assigning random tickets
- [ ] Announcement blog post
- [ ] Make website / leaderboard site ?
- [ ] Close up blog post

We do a public CocoaPods bug bash over a weekend most likely in April where we all hang out in IRC and help people crush some of the smaller annoyances and we can try and deal with the smaller issues. This means we have good running room for Fabio when he's full-time.

/cc @alloy @irrationalfab @kylef

**Comment by orta** [comment]
My best dates are,  April 19/20, April 12/13, then May 10/11

**Comment by orta** [comment]
Figuring @kylef can deal with IRC Bot.

**Comment by kylef** [comment]
Yes, I'll figure all the IRC related stuff out.

**Comment by alloy** [comment]
To be clear, the point is not to actually handle all tickets, that’s just cherry on the cake. The real point is to clean up all tickets:
- [CLEAN] Close no longer applicable tickets.
- [IMPROVE] Reduce ambiguous (error) reports to a simple reproducible description (bonus points for a failing test case commit). Or if it can’t be decided/reproduced it should be closed and asked for usable information.
- [FIX] Actually fixing issues should get extra bonus points.

**Comment by alloy** [comment]
Maybe we should not announce what the prizes are upfront to ensure it stays a friendly event that focusses on helping out with cleaning up?

**Comment by orta** [comment]
> Maybe we should not announce what the prizes are upfront to ensure it stays a friendly event that focusses on helping out with cleaning up?

Makes sense to me. Would be nice to say something like "with prizes from x, y, z" in order to give some attribution beforehand though, rather than a big comprehensive list.

> To be clear, the point is not to actually handle all tickets, that’s just cherry on the cake. The real point is to clean up all tickets.

:+1:

**Comment by fabiopelosin** [comment]
:+1:

**Comment by alloy** [comment]
> Would be nice to say something like "with prizes from x, y, z" in order to give some attribution beforehand though

Yup.

**Comment by orta** [comment]
@alloy / @irrationalfab when are good dates for you?

**Comment by alloy** [comment]
Maybe 28-29 March? Are there any bank holidays coming up in the US that you know of?

**Comment by orta** [comment]
That's feasible for me, looking online it seems the first upcoming US holiday is easter on April 19th - 21st, so probably not of much use without a big delay.

**Comment by alloy** [comment]
Indeed.

**Comment by orta** [comment]
Currently have confirmed prizes of licenses for AppCode, Dash, GIFBrewery
Awaiting replies from two more.

:star2: :star2: :star2:

**Comment by alloy** [comment]
Man, you are _on_ it!

Please also share what we promise them in return (regarding marketing) so we can ensure we do that properly.

**Comment by orta** [comment]
So, from our side we're going to do a blog post ASAP announcing the event, we'll mention it a few times on the CocoaPods twitter on the time coming up to it ( especially if we have blog posts going past it.) if any of our prize sponsors have blog posts / tweets mentioning they're working on this we'll retweet etc on the main account.

Afterwards we'll have a wrap up blog post saying thanks to everyone involved, show a bit of stats, say who won what and then again say thanks to the prize sponsors. :+1:

**Comment by alloy** [comment]
:+1:

**Comment by fabiopelosin** [comment]
Terrific work guys!!!! 28-29 March looks feasible for me as well!

**Comment by orta** [comment]
this happened. It's now completed.
