### ISSUE TITLE
CocoaPods State of the Union during WWDC

### ISSUE THREAD

**Issue by orta** [orta/life#36]
We should do one, but what should it be?

**Comment by dlackty** [comment]
Attended the one last year and really enjoyed the talks about both CocoaPods's recent changes and future roadmap. Guest speaker of related topics (e.g. the one @mattt gave last year) would be also nice.

**Comment by orta** [comment]
Yeah, agreed @dlackty - I've sent an email to the altWWDC lead and will see about doing something like the one last year with them.

**Comment by dlackty** [comment]
:+1: It would be great to hold a lab and any introduction / tutorial session at AltConf to help some newbies.

**Comment by mtitolo** [comment]
I'd be happy to help plan whatever :D

**Comment by supermarin** [comment]
++
- get people together
- provide booze / food
- talk about the 1st bug bash and encourage people to contribute (maybe a quick bootstrap session)
- some abstract talk on the roadmap?
- cocoapods plugins
- ...

**Comment by neonichu** [comment]
I could do a short thing on contributing and bug bash from the n00b perspective, if you'd like.

**Comment by orta** [comment]
Thanks guys, I agree with all the above I think this is definitely the right plan direction.

I figure we should do 2-3 talks:
-  `CocoaPods State of Union` talk that says what we got through this year ( new design, plugins, bug bash, trunk, etc ) and what the direction we think CocoaPods will head. If @irrationalfab is in SF we should get him up for this, and and if he wants I'll join in. ( 30min?)
- I think it'd be cool to have the other devs talk about whatever they want ( 20m each?) 
- I'd love to have @neonichu give a talk about getting involved with CocoaPods via the bash, how he's found learning ruby & browsing the CP codebase. (20min?)

I'll ask @alloy for the Heroku event organizer's details, if we're lucky we might be able to get the same venue maybe. Don't think the alt conf has evening space.

**Comment by mtitolo** [comment]
@orta how large do we expect this to be this year? If Heroku can't sponsor, I can help find another venue. Just need to know the approx # of attendees.

We should also pick a night ASAP.

**Comment by orta** [comment]
I think ~100. Re: timing I was waiting on alt to decide when their bash is, to avoid a clash.

**Comment by alloy** [comment]
Sounds like a very excellent event.

@orta Who at altWWDC did you contact?

**Comment by orta** [comment]
Rob elkin

**Comment by alloy** [comment]
Gotcha.

**Comment by orta** [comment]
Current details:
-  probably gonna do monday & clash with the WWDC evening event, but I'm sure that a lot of people would be interested in our stuff.
- talking with twilio about hosting, they estimate having space for 200 odd.

**Comment by orta** [comment]
Alright, confirmed. 

Monday, 6:30pm @ Twilio
Think we're big enough to pull people in, and there'll be a lot of no-dub dubers

**Comment by mtitolo** [comment]
Monday is not usually an "official" WWDC event, but it's the biggest party night. The WWDC Bash is usually Thursday.

And twilio's space would be great! They are pretty close to Moscone.

**Comment by mtitolo** [comment]
:tada:

**Comment by orta** [comment]
:+1:

**Comment by orta** [comment]
Started writing the details: https://github.com/CocoaPods/blog.cocoapods.org/blob/master/_drafts/CocoaPods-WWDC-Party.markdown

@mtitolo  @supermarin @neonichu  @kylefuller @kattrali 

You all down for doing a 10-20min talk?

@neonichu @supermarin as you both have said in this thread that you're interested I've added you in already. Kyle always says yes to things. And this is obviously separate from the Kucha :+1:

**Comment by orta** [comment]
also, not to be pushy, but if you are, you should think of a topic asap, this might go out to blogs etc via appsterdam so the more filled it is now the better.

**Comment by mtitolo** [comment]
My talk on Private Pods was pretty popular at Renaissance. I could beef it up a bit and give it again. People still don't know much about it.

**Comment by orta** [comment]
> My talk on Private Pods was pretty popular at Renaissance. I could beef it up a bit and give it again. People still don't know much about it.

Agreed, sounds awesome.

**Comment by neonichu** [comment]
I'm in.

**Comment by kylef** [comment]
Of course I'm in, I'm thinking something along the lines of **Creating your first Cocoa Pod** - _From idea to submitting the pod spec in 10 minutes_. This would be an live demonstration.

Other ideas:
- CocoaPod's plugins
- CocoaPod's packager (a teaser of the incomplete plugin)
- _On_ **Repairing Our Broken Specs Repository**.

**Comment by orta** [comment]
@kylef  @neonichu @supermarin @mtitolo - we've got up to 1 hour 30 min for all our talks, so lets try keep them under 20 minutes, ideally around 15.

**Comment by mtitolo** [comment]
👍

**Comment by neonichu** [comment]
:+1:

**Comment by supermarin** [comment]
:+1: :heart:

**Comment by orta** [comment]
thanks all, think we stated the union pretty well :+1:

**Comment by neonichu** [comment]
Especially considering there wasn't much to state ;)
