### ISSUE TITLE
Assign CocoaPods Bug Bash Prizes

### ISSUE THREAD

**Issue by orta** [orta/life#37]
@neonichu @segiddins @joelparsons @confidenceJuice @frosty @z00b @apalancat @davelyon @lazerwalker @lukabratos @siuying @colinmcardell @supermarin @AhmadAlokush @samuelwford @dbgrandi @dlackty @alexrothenberg @schneiderandre @w5mith @luisdelarosa @lrz @jefflovejapan @theyonibomber @klaaspieter @IchabodDee @cescofry

Hello everyone who contributed to the CocoaPods bug bash! 

Thanks a million times, you guys got a _huge amount_ done, and me and the rest of the team are SUPER IMPRESSED.

![gif](http://imgur.com/download/T7M5cph)

So I've made a google spreadsheet that lets people grab a license of one of the apps we've been given, I have asked the top 5 already to grab their choice so from here it's pretty much a cool fee for all :+1: - I love all these apps and use them daily, they're all ace.

https://docs.google.com/spreadsheet/ccc?key=0AuSbFEV0ER0udDZQV0pNNXBROXdFV1lITXZteWVTVXc&usp=sharing

ps. sorry if the timezone sucks for you, as WWDC knows this kinda thing

**Comment by marcboquet** [comment]
Thanks to you and the rest of the team, CocoaPods is essential for many of us!
![giphy](https://cloud.githubusercontent.com/assets/14408/2604697/1f3d69e8-bb3d-11e3-94f9-668922e9f92c.gif)

**Comment by schneiderandre** [comment]
No, we thank you for your time and effort. I've learned a lot about Ruby and CocoaPods. Thanks also to @orta and especially @alloy for their kind support during the Bug Bash.
![awesome](http://awesomegifs.com/wp-content/uploads/carl-sagan-youre-awesome.gif)

**Comment by neonichu** [comment]
👍👍👍👍👍, would bug bash again.

**Comment by lazerwalker** [comment]
![superstock_4193r-1646](https://cloud.githubusercontent.com/assets/821238/2605045/76e82720-bb40-11e3-87d3-f75545df805f.jpg)

**Comment by dbgrandi** [comment]
Would _**definitely**_ bug bash again. `.claim` had me on the edge of my seat.

**Comment by luisdelarosa** [comment]
Thanks to @alloy, @orta, @irrationalfab and everyone! :heart: It was definitely a pleasure to hangout in IRC and the bot worked pretty well too. Go CocoaPods go! Will this be a yearly kind of thing?

**Comment by neonichu** [comment]
@luisdelarosa You can actually bash CocoaPods bugs all year round! :)

**Comment by orta** [comment]
Think we could definitely do something around helping people getting set up to contribute PRs back etc, it seemed to be a very positive side effect of the bash format.

**Comment by lazerwalker** [comment]
Yeah, I've really been enjoying seeing the "easy patch of the day!" tweets from the official @cocoapods account the past few days.

**Comment by orta** [comment]
Yeah @irrationalfab has done a great job with that!

**Comment by dlackty** [comment]
Thank you all for this event. It's so great to see some of my codes merged into CocoaPods which I use almost everyday since it was released.

**Comment by AhmadAlokush** [comment]
I think this would be beneficial, also for non ruby devs a low barrier entry into cocoapods could be useful, I volunteer to write up a tutorial if someone can walk me through it( not a ruby dev myself).

Sincerely,
Ahmad

**Comment by fabiopelosin** [comment]
Really nice to hear the the Bug Bash, ended up being so well received...

![gif](http://i.imgur.com/GixGhUw.gif)

@AhmadAlokush I would gladly help you because you have the perspective of a new contributor... I would suggest to open an issue in CocoaPods/guides.cocoapods.org and then we can start discussing it.

**Comment by schneiderandre** [comment]
@AhmadAlokush, @irrationalfab a tutorial is a great idea. I'm not a Ruby dev and started to play with it a day before the Bug Bash. But setting up the CocoaPods development environment was a very painstaking process for a Ruby beginner. I would also love to help and share my experience.

**Comment by fabiopelosin** [comment]
Ace!

**Comment by AhmadAlokush** [comment]
@irrationalfab , created issue, https://github.com/CocoaPods/guides.cocoapods.org/issues/68
would be willing to discuss the details.

**Comment by samuelwford** [comment]
Awesome experience; so glad I got to be part of it!

**Comment by frosty** [comment]
I really enjoyed the weekend, and felt like I learnt quite a lot. You guys
were always patient with all my questions and helped me along the way.

Next stop, start getting some pull requests in!

Thanks for a great event!

**Comment by orta** [comment]
Thanks guys, I've passed on all the details now, thus this issue can be closed now. Rock on.
:+1:
