### ISSUE TITLE
CocoaPods events Code of Conduct

### ISSUE THREAD

**Issue by neonichu** [orta/life#38]
I have mostly been out last week, but really want this to happen before our next events. I think @alloy has already agreed on a text, we just need in online somewhere. We would also need a inclusivity@ email address. You're doing the web stuff, right?

**Comment by neonichu** [comment]
Would be happy to do the work involved myself OFC, just need to enable to do it, then.

**Comment by orta** [comment]
http://cocoapods.org/legal

**Comment by neonichu** [comment]
👍, your 🍻 will be on me tonight!

**Comment by neonichu** [comment]
One suggestion, maybe say "Legal / Inclusivity" or something in the footer, as legal is something people often don't look at.

**Comment by neonichu** [comment]
FWIW:

```
$ curl -I https://cocoapods.org/legal
```

curl: (7) Failed connect to cocoapods.org:443; Operation timed out

HTTP works, though - footer links HTTPS.
