### ISSUE TITLE
NYC iOS Beginner Conference

### ISSUE THREAD

**Issue by orta** [orta/life#42]
- Hosted with @jmburges
- 20m talks
- All Day Friday Aug 29 2014
### Focus:
- Aimed at people beginning with, or interested in learning about making iOS Apps. 
### Structure:
- 3-4: If you were starting now, what would you want to know?
- 3-4: What makes objective-c a unique language? /. The Story of building my First App?
- 3-4: What are you learning about swift now we're all beginners?
### Speakers Invites:

Keeping speakers to NYCers, as plan isn't to charge much, only nominal fee to make people actually turn up. Makes it as accessible as possible.

**Comment by orta** [comment]
Hello there [NAME OF PERSON]

Joe Burgess & I are planning a full day beginners iOS conference in NYC in on a Friday in late August at the FlatIron School - open to the public. We'd love it if you were involved as a speaker. We've come up with a 3 major topics around which we'd like the talks to be based. 
- If you were starting now, what would you want to know?
- What makes objective-c a unique language? /. The Story of building my First App?
- What are you learning about swift now we're all beginners?

If any of these questions resonate with you, and you're interested in speaking, please comment on this issue and we'll keep everyone in the loop. If it's not up your alley, feel free to unsubscribe and either comment or let one of us know privately,

/cc @irace @kathleenyanolatos @dstnbrkr @mbrandonw @1aurabrown @RobRuffler @oxling @yujean @Dasmer

**Comment by ashfurrow** [comment]
Looks super cool! Wish I could be there :smile: If there is anything I can do to help, like give away copies of books or something, please let me know.

**Comment by kathleen** [comment]
I wish I could, but I'll be in Japan then :frowning: If there's anything I can do to help, please let me know!
Also, I would definitely like to participate in any future event.

**Comment by jmburges** [comment]
Also, anyone have any brilliant ideas on names?

**Comment by jmburges** [comment]
@orta opinions on making a github repo to contain all of the abstracts for talks and then do submissions via pull requests?

**Comment by irace** [comment]
@orta I'm happy to participate. I don't have any great talk ideas but I'm sure I can come up with something that falls within the bounds of what you're asking for, especially if it's only 20 minutes and not until the end of August.

**Comment by jmburges** [comment]
I kinda really suck at design but [here](http://jmburges.github.io/beginner-ios-conf-website/) is a first stab. We need a proper name. Also it just generally needs work to look reasonable. Not shooting for anything incredibly beautiful...but it should be workable!  Github repo at [jmburges/beginner-ios-conf-website](https://github.com/jmburges/beginner-ios-conf-website)

**Comment by orta** [comment]
Cool @irace - I think the questions are vague enough to allow for a lot of wiggle room.

@jmburges - I was thinking about `Swift.start()` as a name earlier? I can fork this and make it work. :+1:

**Comment by mbrandonw** [comment]
+1 I'll give a talk and help out in any way.

**Comment by dasmer** [comment]
I'd love to give a talk too. Let me know how I can help!

**Comment by 1aurabrown** [comment]
@orta i may be out of town, keep me as a maybe until I know for sure.

**Comment by orta** [comment]
one of our Artsy Designers, whose been working on the app with me to accidentally invited herself to speak - added @katarinabatina to the list

**Comment by yujean** [comment]
I'm interested in giving a talk, although I don't have a topic!  Ahh

**Comment by oxling** [comment]
Hey - sounds awesome; unfortunately I'm going to be out of town that week.

**Comment by bpapa** [comment]
As I said on Twitters, I'll be too busy getting ready for my H.S. class then to prepare any kind of talk, but if you need help with things that don't require any prep (helping out, q&a, etc) I'm game.

**Comment by orta** [comment]
@bpapa : Sounds good
@oxling : Shame! Thanks for letting us know

I've updated the website with some of the confirmed, http://orta.github.io/beginner-ios-conf-website/

**Comment by segiddins** [comment]
Need anyone else to speak?

**Comment by orta** [comment]
@segiddins yeah, if you're interested, I'd definitely be interested in hearing you speak.

**Comment by segiddins** [comment]
Awesome :)

**Comment by orta** [comment]
puts us at 7 confirmed so far :+1:

**Comment by jmburges** [comment]
woot! Talked to danny and he's out of town that week. Finishing up some website stuff and eventbrite stuff right now

**Comment by orta** [comment]
Awesome. Also, I think you'd have a good perspective on what people new to iOS should hear @jmburges - we should get you on the list.

**Comment by jmburges** [comment]
Made some changes. http://jmburges.github.io/beginner-ios-conf-website/
- I talked to @ebjacobs and she said if we make it $30 we can provide breakfast and lunch and all that so I upped it to $30...I don't think people will mind.
- Added a new topic that I would love to hear about "How do we maintain the great parts of Objective-C in Swift?".
- Also updated the tag line so that we don't scare away existing obj-c devs. "A One Day Conference for 
  developers new to Swift"
- The Legal stuff is kinda hilarious....Do we want to just link them directly to [Flatiron's Code of Conduct](http://flatironschool.com/code-of-conduct.html)?
  - Also aswiftstart.com is available so buying that bad boy. As soon as the dns and all that goes through I'll link up the site to github and unpassword protect the eventbrite.

**Comment by orta** [comment]
bringing in @dbgrandi who I think would do an awesome job here too, are you free for this friday?

**Comment by dbgrandi** [comment]
@orta, I'd love to be there, but will unfortunately be away for an extended labor day weekend.

Sign me up for the next one (I'd love to tell the story of building my first app), and let me know if I can help in any other way.

**Comment by jmburges** [comment]
Hey @orta CHECK IT OUTTTTTTTTT http://aswiftstart.com/

**Comment by orta** [comment]
Alright, this looks awesome, make an announcement tweet etc, I'll ping meetups in the area tomorrow about an announcement. My internets being a bit naff so I'll try do some stuff tonight but it's likely that I'll do everything tomorrow.

**Comment by robruffler** [comment]
@orta would love to participate, but I'm moving to a new apartment right around this time and I won't have the bandwidth to contribute in a meaningful way. Let me know if I can help in some other way this time around.

**Comment by neonichu** [comment]
Hope you are doing recordings, wanna catch that @segiddins talk :)

**Comment by orta** [comment]
Of interest is a common "being an indie" thread, I think someone could do a really nice talk summarising why someone went indie, how it's working out for them, and what they think their future of indie-ness is.

@robruffler - currently looking for 2-3 more people, got some in the pipeline but definitely interested. I'd love some stories of how the Nick apps got made.

**Comment by hamin** [comment]
@orta I'm game, let me know if you need me :)

**Comment by orta** [comment]
Sounds great @hamin - do you have a better photo that your gravatar? And what would you like your bio to say?

**Comment by katarinabatina** [comment]
Orta what should I talk about and for how long???

Katarina

**Comment by orta** [comment]
@katarinabatina - I think it'd be interesting to talk about what the relationship of app developer and designer is like, what developers can do to make life easier for designers ( and vice-versa ) and what design resources you'd recommend. As the conference is focused on people before they get into roles like ours. It's a 20 minute talk, I can go over some of the ideas in person.

**Comment by hamin** [comment]
@orta @katarinabatina interesting, for the glimpse relaunch/re-design i've actually paired with our desginer a lot :)

@orta what size photo do u need? Let me get back to you on the bio. I suck at those :)

**Comment by orta** [comment]
_Everyone_ - If you've had the chance to have a think around what topic you're talking on it would be nice to let us know so that we've not got conflicts. 

@hamin - around 460x460 would be good.

**Comment by yujean** [comment]
I'm going to talk about what it was like making my first app.

**Comment by irace** [comment]
I'm going to talk about being a language-agnostic developer, and the importance of familiarizing yourself with concepts rather than syntax.

**Comment by orta** [comment]
@hamin - bio shot?

**Comment by hamin** [comment]
@orta http://harisamin.com/images/about.png

**Comment by segiddins** [comment]
I'm going to talk about working with other people's code

**Comment by lacyrhoades** [comment]
I'm going to talk about provisioning / certificates / developer identities.

**Comment by hamin** [comment]
@orta is there a website up for the event? still thinking about what to talk about...i have a few ideas, on being push notifications and understanding when what gets called sans background fetches....not sure though, is there something that someone has not yet mentioned that would be good to talk about?

@lacyrhoades good call on your topic...i know i had a LOT of problems when i started out with that

**Comment by lacyrhoades** [comment]
@hamin thanks I wish I could take credit but props to @orta for the idea

**Comment by orta** [comment]
@hamin - http://aswiftstart.com 

I'll have a think tonight for one, but here's 5 questions from the site to provoke talk ideas

> If you were starting now, what would you want to know?
> What makes Objective-C a unique language?
> Stories from your first app
> What interesting topics are you learning about in Swift?
> How do we maintain the great parts of Objective-C in Swift?

**Comment by hamin** [comment]
@orta so I was definitely thinking more along 1 and 2 and here's what i came up with: Cocoa Design Patterns

Basically thinking of giving an intro on 3 design patterns that can be used to do the same-ish things for pub-sub-ish reasons
- NotificationCenter
- KVO
- Delegates (implementing a delegate protocol and using it)

Definitely things I wish I knew more about when i was starting and I think definitely makes Objective-C unique, multiple interesting ways/patterns to achieve similar things. 

I think this is around 15-20 minutes. What do you think? Open to other suggestions.

**Comment by mbrandonw** [comment]
Oh, I haven't really responded to this, but I'm more in the no. 4 bucket:

> What interesting topics are you learning about in Swift?

**Comment by orta** [comment]
Both sound great!

**Comment by segiddins** [comment]
@orta has a speaker schedule been worked out yet? I need to give a talk at work sometime in the lunch hour

**Comment by orta** [comment]
OK then, what I think is the current schedule:

| Person | Time | Topic |
| --- | --- | --- |
| Dasmer Singh | 10:30 | - |
| Brandon Williams | 11:00 | Something about Swift |
| Eugene Yee | 11:30 | Making my first app |

30m  Break - 

| Person | Time | Topic |
| --- | --- | --- |
| Lacy Rhoades | 12:30 | Certs, Profiles & Identities |
| Katarina Batina | 1:00 | Working with Designers |
| Danny Hertz | 1:30 | - |

1hr Break - 

| Person | Time | Topic |
| --- | --- | --- |
| Haris Amin | 2:30 | Intro to Obj-C design Patterns |
| Sam Giddins | 3:00 | Working with other people's Code |
| Byran Irace | 3:30 | Being Language Agnostic |
| JP | 4:00 | - |

Does this work for everyone?

**Comment by lacyrhoades** [comment]
Looks good to me. I don't have to talk for an hour though right?

**Comment by orta** [comment]
doh, fixing!

**Comment by jmburges** [comment]
We forgot about @dannyhertz !  Any ideas what you'd like to talk about Danny?

**Comment by dannyhertz** [comment]
Hey!I'm going to talk about switching from web to iOS development. I'll focus on my first year of iOS development and the resources I used to get up to speed quickly. Cool?

**Comment by orta** [comment]
:+1: I was literally writing the schedule o the site right now, sounds perfect.

**Comment by mbrandonw** [comment]
@orta Do you know if there's a spot at Flatiron school for me to park my bike inside?

**Comment by jmburges** [comment]
@mbrandonw Yup! It's off our back entrance on Greenwich st. When you walk in the door, immediately turn right and there is a gold door. Open that up and a bike rack!

**Comment by mbrandonw** [comment]
@jmburges sweet! thanks!

**Comment by orta** [comment]
![http://i.imgur.com/AQpnFkD.gif](http://i.imgur.com/AQpnFkD.gif)

So. 

### Thanks everyone.

This was a really cool experience, I think as a collective you inspired and lighted the imaginations of our audience. Every person I spoke to was extremely impressed by the speakers and hoped there would be another. I know I've come out of it with a lot more than I put in. 

I've written my write up on my [blog, rebase](http://orta.io/rebase/a-swift-summary/).

That said, I'm a little bit sad to hit the close and comment button below. I need to grab some beers with Joe at some point, but maybe this is something we can repeat, if it is I'd like you lot to think about who you think might be a good speaker on a similar theme.

**Comment by hamin** [comment]
@orta @jmburges thanks a lot had a blast :)

**Comment by jmburges** [comment]
just putting My :+1: in here!

Pretty amazing first round at this. Definitely something that should happen again. Mostly really amazing to get the NYC community together for a day! What a great bunch of people :)

**Comment by yujean** [comment]
Joe & Orta thank you so much for putting this together!  It's always
impressive when a few people can organize an event that helps many.

I'd love to help out with any future conferences!

**Comment by jmburges** [comment]
@irace @katarinabatina @mbrandonw @Dasmer @yujean @segiddins @lacyrhoades @hamin @dannyhertz  Do you mind posting your slides to slideshare? I would love to update the website with your amazing slides :). Thanks!

**Comment by mbrandonw** [comment]
Sure, I've got a pdf of my slides and the playgrounds I worked with here: https://github.com/mbrandonw/presentations/tree/master/2014-08-29-a-swift-start

**Comment by segiddins** [comment]
https://speakerdeck.com/segiddins/working-with-other-peoples-code

**Comment by irace** [comment]
https://speakerdeck.com/irace/dont-be-an-objective-c-or-a-swift-developer

**Comment by dasmer** [comment]
https://speakerdeck.com/dasmer/learn-from-thy-users

**Comment by hamin** [comment]
SpeakerDeck: https://speakerdeck.com/harisamin/intro-to-obj-c-design-patterns-or-or-how-i-learned-to-be-less-bad

SlideShare: http://www.slideshare.net/harisa1/intro-to-obj-c-design-patterns

**Comment by orta** [comment]
For @katarinabatina http://cl.ly/2p2q441R1M0y/artsyPresentation_DesignForiOS.pdf

**Comment by orta** [comment]
Found @hamin's on his speaker deck: https://speakerdeck.com/harisamin/intro-to-obj-c-design-patterns-or-or-how-i-learned-to-be-less-bad

**Comment by dannyhertz** [comment]
Mine's at https://speakerdeck.com/dannyhertz/my-first-year-with-ios

**Comment by yujean** [comment]
Mine's uploading now, and should be done by the time you read this  :)

https://speakerdeck.com/yujean/power-of-one

**Comment by jmburges** [comment]
Thanks everyone! I linked to everyone's decks on the main website.

Also! We made a [feedback survey](https://flatiron.typeform.com/to/BsioIX) I'd love for the speakers to fill out.

cc: @irace @katarinabatina @mbrandonw @Dasmer @yujean @segiddins @lacyrhoades @hamin @dannyhertz @jpsim

**Comment by jpsim** [comment]
My slides: https://speakerdeck.com/jpsim/how-do-i-app. I'll fill out the survey.
