### ISSUE TITLE
Make an Xcode plugin to Clean & Rebuild when pch fails

### ISSUE THREAD

**Issue by orta** [orta/life#45]
`fatal error: file '/Users/orta/dev/ios/energy/Classes/Util/ARDispatchManager.h' has been modified since the precompiled header '/Users/orta/Library/Developer/Xcode/DerivedData/Artsy_Folio-ghxcsgfcywgwahavglmkgqcctgzk/Build/Intermediates/PrecompiledHeaders/ArtsyPartner-Prefix-fsszpmpqiwrrzlfpwxujdxdsakqu/ArtsyPartner-Prefix.pch.pch' was built`

**Comment by alloy** [comment]
http://openradar.appspot.com/18536864

**Comment by orta** [comment]
@alloy did this!

**Comment by orta** [comment]
https://github.com/alloy/AxeMode/
