### ISSUE TITLE
Mail out CocoaPods Contributor Coins

### ISSUE THREAD

**Issue by orta** [orta/life#49]
Hi there everyone. Before reading any further into this issue you should read this: http://blog.cocoapods.org/Coins/

You're in the top 80 contributors to CocoaPods, and that means I have to try and get one of these things to you. Given that this is a pretty time consuming and expensive to try and mail these out individually I'd like to make a spreadsheet where you can put down your name + city + country and I can send it to a single person in an area

-> https://docs.google.com/spreadsheets/d/1YJK7bqlWs_9KGbQgb8AA_ygkudBMtB_uaZDs9HLYZUc/edit?usp=sharing

/cc @fabiopelosin, @alloy, @orta, @floere, @segiddins, @kylef, @neonichu, @lukeredpath, @AliSoftware, @Keithbsmiley, @mtitolo, @Kapin, @nolanw, @goonzoid, @mrackwitz, @siuying, @supermarin, @jasl8r, @yas375, @dbgrandi, @subdigital, @kommen, @ianyh, @xslim, @swizzlr, @pietbrauer, @pbernery, @0xced, @clarkda, @mk, @jweinberg, @carsonmcdonald, @Manfred, @nevyn, @fmccann, @k0nserv, @squarefrog, @luisdelarosa, @tayhalla, @dlackty, @gfontenot, @blakewatters, @Thomvis, @joe-loco, @groue, @AshFurrow, @heyzooi, @dev4dev, @croach, @farcaller,

**Comment by orta** [comment]
I can't include 80 people on a comment, so. You're in the top 80 contributors to CocoaPods, you should read this: http://blog.cocoapods.org/Coins/ - then look at the full issue!

@samstewart, @dlvenable, @dcutting, @nskboy, @Ashton-W, @rivera-ernesto, @lazerwalker, @phatblat, @ulrikdamm, @chriseidhof, @drodriguez, @olarivain, @MaxGabriel, @schneiderandre, @andreamazz, @nmccann, @Lascorbe, @dhoerl, @Noreaster76, @l4u, @seivan, @netbe, @paulyoung, @kattrali, @fluidsonic, @alexrothenberg, @martincik, @btaylor, @listrophy, @modocache and @atomkirk

**Comment by kattrali** [comment]
That postage must be unreal! :smile_cat:

**Comment by Ashton-W** [comment]
Are they filled with chocolate?

**Comment by orta** [comment]
Nope all metal, https://www.madebycooper.co.uk/products/coins/die-struck-coins my glass of them is really heavy

**Comment by groue** [comment]
Quite a delicious surprise :smile:

**Comment by pbernery** [comment]
Nice surprise indeed.

**Comment by xslim** [comment]
Hey Orta! I really appreciate the gesture! 
As I'm trying to live a minimal life, I would like someone else to enjoy this nice present :)
Anyway, I would be glad to drink a coffee with any contributor in Amsterdam ;)

**Comment by Manfred** [comment]
Thanks, this is really awesome.

**Comment by pietbrauer** [comment]
Nice, hope I am not the only contributor in Germany though. But I would be able to send out to all the people in Germany I think.

**Comment by andreamazz** [comment]
That's crazy! What an awesome surprise, and a great honor. :+1:

**Comment by yas375** [comment]
Amazing! Thanks a lot!

On Thu, Oct 23, 2014 at 10:27 AM, Andrea Mazzini notifications@github.com
wrote:

> That's crazy! What an awesome surprise, and a great honor. [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orta/life/issues/49#issuecomment-60201787.

## 

Victor Ilyukevich.
@yas375

**Comment by Lascorbe** [comment]
This is super cool! Thank you! :wine_glass:

**Comment by ashfurrow** [comment]
I'll be in NYC in a few weeks – I can bring back the coins for other contributors based in The Netherlands (provided they don't cause me to exceed my baggage weight limit :stuck_out_tongue:). 

Also @xslim I don't think I've seen you at the Appsterdam meetups – happy to meet and have a coffee some time!

**Comment by iamladi** [comment]
Wow. This is really cool. Thank you! :)

**Comment by mrackwitz** [comment]
This is indeed super cool!

@pietbrauer: No, you are not the only from Germany. Besides you, there is @neonichu, @chriseidhof, @mk and me at least. Did I forget anyone?

**Comment by k0nserv** [comment]
Great initiative @orta. Super glad to be included and more importantly to have CocoaPods in the iOS toolkit, can't imagine life without it.

**Comment by ulrikdamm** [comment]
This is so cool. Guess I'm the only one in Denmark though?

**Comment by paulyoung** [comment]
❤️

**Comment by floere** [comment]
@ulrikdamm No, I am also living in Denmark - at least until mid-December :)

**Comment by yas375** [comment]
I have an idea: how about creating a map after all with people marked on it just to see from what countries people contribute to CocoaPods. For example it may look something like [this](https://gist.github.com/yas375/47927f8c18769506e025). Actually, why not to include such maps described with geojson into the repositories of open source projects so it may encourage people to contribute as well when they see someone from their city contributed to the project :)

**Comment by seivan** [comment]
Is it possible to donate ones share (or the cost of ones share & posting) to charity?

**Comment by AliSoftware** [comment]
What a nice surprice! Guys, you are awesome!
(And @yas375  :+1: for the map after we have all the contributor's cities!)

**Comment by tayhalla** [comment]
Hey @orta & team, pretty awesome of you all to do this. Thanks!

**Comment by dbgrandi** [comment]
What an incredible gesture. Thanks!

**Comment by subdigital** [comment]
Indeed, very honored.  Thanks, @orta!

## 

Ben Scheirman

**Comment by squarefrog** [comment]
Haha that is awesome! Cheers @orta

**Comment by lazerwalker** [comment]
Another +1 for "this is ridiculously awesome". Well done, @orta :+1:

**Comment by listrophy** [comment]
Thank you @orta!!!! :heart: :heart: :heart:

**Comment by dlvenable** [comment]
That is a nice surprise and great idea! Thanks for thinking of us, @orta.

**Comment by swizzlr** [comment]
This is so wonderfully lovely. I'm in NYC, and I can meet you. This is so touching.

**Comment by supermarin** [comment]
@orta :heart: :green_heart:

**Comment by btaylor** [comment]
![de2ff](https://cloud.githubusercontent.com/assets/2042/4756773/0e62772a-5ad0-11e4-818a-0f40e2f88bda.jpg)

:trophy:

**Comment by ashfurrow** [comment]
@btaylor I'm picturing @orta or @alloy as Bad Cop and Lord Business, respectively.

**Comment by tayhalla** [comment]
I’m going to get some superglue and smack this on the outside of my macbook. Sticker flare isn't cuttin' it nowadays :)

**Comment by paulyoung** [comment]
![kraglepods](https://cloud.githubusercontent.com/assets/84700/4757895/c25205d4-5ada-11e4-95a7-b3e2298de6e8.png)

**Comment by ashfurrow** [comment]
I laughed so hard I had a coughing fit.

**Comment by dev4dev** [comment]
:bowtie: :sparkles: :sparkles: :tada:

**Comment by dustywusty** [comment]
@orta this is awesome! :heart:

**Comment by orta** [comment]
![Giphy](http://media0.giphy.com/media/13yNFN1TlNCjC0/giphy.gif)

**Comment by olarivain** [comment]
Wow, such amazing, much delightment.

This is pretty awesome :)

**Comment by drodriguez** [comment]
Amazing surprise. Thank you very much!

**Comment by AliSoftware** [comment]
@btaylor @paulyoung looool Awesome!!

**Comment by schneiderandre** [comment]
![You are awesome!](http://i.imgur.com/Gg0Pk.jpg)

**Comment by netbe** [comment]
catching up after a week vacation, that's an awesome surprise!

**Comment by goonzoid** [comment]
This is a wonderful gesture - thank you so much!

**Comment by orta** [comment]
Europeans, I've given a bunch to @AshFurrow to deal with
I think I've dealt with the Russians
NYCers: [iOS SOHO](http://www.meetup.com/iOSoho/events/207557752/)?

Will start figuring out SF + World later in the week

**Comment by ashfurrow** [comment]
I'm based in Amsterdam but will be visiting Minsk and Halifax, Nova Scotia in the next few weeks. Anyone feel free to get in touch if you're nearby either of those cities.

**Comment by lazerwalker** [comment]
@orta I'm waitlisted for next week's iOSoho. You think folks'll be hitting up a pub afterwards?

**Comment by phatblat** [comment]
KraglePods, ha! @paulyoung you've "coined" a new term.

**Comment by lazerwalker** [comment]
@phatblat
![1333521-facepalm](https://cloud.githubusercontent.com/assets/821238/4920618/b8ada154-6503-11e4-9a20-db7182d639c7.jpg)

(:heart:)

**Comment by paulyoung** [comment]
@orta I'm out of the country for the meetup next week but will be at the following two.

**Comment by modocache** [comment]
> @orta I'm out of the country for the meetup next week but will be at the following two.

Ditto for @Noreaster76 and I. Can we all shoot for coins and drinks at the December meetup?

**Comment by yas375** [comment]
Coins are in Minsk! :)

![image](https://cloud.githubusercontent.com/assets/217368/4950269/b8fbe03e-6658-11e4-8dcd-a42e3e3807a9.jpg)

**Comment by dcutting** [comment]
Hi guys, did any of the coins make it over to London yet? I'd love to collect one if somebody has a stash!

**Comment by orta** [comment]
Hello everyone, if you've not got a coin by now, or I've not contacted you because I can get a group sent out can you please email me your address at `orta @ thecocoapodssite` and I'll get them mailed out!

The spreadsheet is up to date to my knowledge, https://docs.google.com/spreadsheets/d/1YJK7bqlWs_9KGbQgb8AA_ygkudBMtB_uaZDs9HLYZUc/edit#gid=0

**Comment by groue** [comment]
Salut les Français @pbernery and @AliSoftware - what about asking @orta to send our coins to Paris? I'd send @AliSoftware's one to Rennes. @orta, would it be OK for you?

**Comment by orta** [comment]
That would be lovely @groue - email me your address  :)

**Comment by pietbrauer** [comment]
I still have the German ones :( and I suck at collecting addresses. So could the 6 other Germans send me theirs? Will send them out next week then.

**Comment by groue** [comment]
`orta @ thecocoapodssite` is not very clear... @orta You can mail me at `gr <at> pierlis.com` :-)

**Comment by heyzooi** [comment]
I guess that thecocoapodssite means cocoapods.org

**Comment by pbernery** [comment]
@groue sounds good to me. Thanks!

**Comment by Ashton-W** [comment]
I haven't been paying close attention to the organisation of this. ~~Did you want to send all the Australia/New Zealand coins for distribution locally, @orta?~~

Didn't realise I might be the only one down here (unless some of the unknown locations are too). I'll email you Orta.

**Comment by AliSoftware** [comment]
@groue I'll go to dotSwift Paris tomorrow and @ashfurrow should normally bring mine there, so I should be good :) 

@orta maybe wait after this week-end to mail them to the frenchies (in case @groue and @pbernery get theirs at dotSwift too for example — if Ash has enough coins for  that is — or on the contrary if we forget to get them during the week-end, etc)

**Comment by pbernery** [comment]
I won't be at dotSwift but should be at the bar after the conferences.

**Comment by fluidsonic** [comment]
@pietbrauer thank you that you take care of the German coins :+1: 
Where can we send you our addresses?

**Comment by pietbrauer** [comment]
@fluidsonic piet <at> nerdishbynature.com :)

**Comment by AliSoftware** [comment]
@orta: I'm leaving Paris right now and didn't have a chance to catch up with @ashfurrow sadly :-/ so let's mail them.

**Comment by Lascorbe** [comment]
I'll be at SwiftSummit this weekend, if anyone who have coins is coming let me know! 😃

**Comment by orta** [comment]
Everything is now mailed. Sorry non-americans, it took a long time to get all the additional paperwork for you sorted.

If you don't get anything in the next few months, email me, my address is on my github profile.

![Giphy](http://media0.giphy.com/media/Rbsz78NuhUcZW/giphy.gif)

**Comment by AliSoftware** [comment]
@groue are you the one supposed to receive all french coins and send mine back to me?

**Comment by groue** [comment]
@AliSoftware, I can, but I haven't seen any coin yet :-)

**Comment by heyzooi** [comment]
I got my coin! Thanks @orta!

**Comment by luisdelarosa** [comment]
I received mine too. Thanks so much @orta! Go CocoaPods team go!

**Comment by Ashton-W** [comment]
Got my coin! Thanks @orta :love_letter:

**Comment by AliSoftware** [comment]
@groue any news?

**Comment by groue** [comment]
Hi @AliSoftware, @orta ! No I didn't get any coin yet. Should I? Did I miss something?

**Comment by farcaller** [comment]
Tentative bump, I wonder if the distribution is over?

On Wed, Apr 29, 2015 at 7:08 AM, Gwendal Roué notifications@github.com
wrote:

> Hi @AliSoftware https://github.com/AliSoftware, @orta
> https://github.com/orta ! No I didn't get any coin yet. Should I? Did I
> miss something?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orta/life/issues/49#issuecomment-97317530.

## 

Sincerely,
Vladimir "Farcaller" Pouzanov
http://farcaller.net/

**Comment by jweinberg** [comment]
I also never got mine, sad day :(

**Comment by gfontenot** [comment]
I have two that still need to be delivered: One for @jasl8r and one for @ianyh.

**Comment by orta** [comment]
@farcaller / @jweinberg email me at orta.therox % gmail.com - and I'll send out some more
@groue - I'll have to send a second set out to you too, any chance you can forward me your details again?  I've got spares to deal with this kind of thing.

**Comment by AliSoftware** [comment]
@orta still haven't received mine either 😢
(You told me two weeks ago in Slack that you'd try and send some from the UK… I'm not sure you had time to do it yet but if you did, I still haven't received them)

**Comment by pbernery** [comment]
same here, haven't receive it yet.

**Comment by orta** [comment]
Email me, the same applies to everyone on this thread, please remember you're on messaging 50-odd people with every comment. 

@AliSoftware, @pbernery  you were included in the french ones that seem to have disappeared mid-flight.

**Comment by pietbrauer** [comment]
I still have a spare one and could send from Germany.

**Comment by AliSoftware** [comment]
Bad news @pbernery @groue I received the envelope Orta sent me, but it was actually already semi-open and empty on arrival :disappointed: Seems like the weight of the coins made the envelope open during transport and they got lost (or some dishonest postman?).

**Comment by pbernery** [comment]
Bad news indeed, that's a shame.
