### ISSUE TITLE
Go mountain running with Chris Eidhof in January

### ISSUE THREAD

**Issue by orta** [orta/life#6]

**Comment by chriseidhof** [comment]
Can I use this space for comments? 

If yes, here are some options (more to be added?): [Lake District](http://en.wikipedia.org/wiki/Lake_District), [Harz](http://en.wikipedia.org/wiki/Harz), [Riesengebirge](http://en.wikipedia.org/wiki/Krkonoše).

**Comment by orta** [comment]
Sure thing, I was thinking the 18th & 19th of January. 

The germanic hills sound amazing! I'm game for any of these as me and my girlfriend were planning on going to the Lake District at some point to do some walking in the hills. So we could make it a "saturday run", "sunday walk" affair.

**Comment by chriseidhof** [comment]
Awesome. I might not be in Europe then, but if I am, we have a date.  

The only thing is: there is a good chance that there’s lots of snow. Haven’t run there in the winter before. But worst case, you can come to Berlin, crash my couch and we’ll run in the hills around Berlin. Would still be lots of fun.  

## 

Chris Eidhof

**Comment by chriseidhof** [comment]
We should totally do this! It's a shame we haven't done it yet, so we need to reschedule...

**Comment by orta** [comment]
I'm calling this OK, we've done mountains, and we've ran ;)
