### ISSUE TITLE
Make new ARAnalytics build & add local storage support

### ISSUE THREAD

**Issue by orta** [orta/life#9]
https://github.com/orta/ARAnalytics/issues/39

Also open to letting Dan beat me to the punch.

**Comment by Daniel1of1** [comment]
Very close to creating a life Repo to which this could totally be an issue. Likely I will go for it (local analytics) over christmas (i.e after alt Tech Talks London) if you haven't already.

**Comment by orta** [comment]
closing, if I can delay this long isn't worth it for me :)
